### ISSUE TITLE
-0-

### ISSUE THREAD

**Issue by jesdicaDomo** [CreeperGo/mynpc#7]
Notice: Object of class pocketmine\nbt\tag\StringTag could not be converted to int in phar:///home/sutimon/zb/PocketMine-MP.phar/src/pocketmine/item/Item.php on line 396
[17:39:30] [Server thread/INFO]: 恭喜玩家AceChain8855457擊殺了

**Comment by CreeperGo** [comment]
Oops,Could you give me the call stack before the Notice?

**Comment by RexRed6802** [comment]
It fixed at 19:09 on 10/1 in 2016
